# Generated by Django 6.1 on 2026-08-20 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم القالب')),
                ('channel', models.CharField(choices=[('email', 'البريد الإلكتروني'), ('sms', 'رسالة نصية'), ('in_app', 'إشعار داخل البوابة')], db_index=True, max_length=20, verbose_name='قناة الإرسال')),
                ('subject', models.CharField(blank=True, max_length=250, verbose_name='عنوان الرسالة')),
                ('body', models.TextField(verbose_name='محتوى الرسالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='القالب نشط')),
            ],
            options={
                'verbose_name': 'قالب رسالة',
                'verbose_name_plural': 'قوالب الرسائل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان الإعلان')),
                ('content', models.TextField(verbose_name='محتوى الإعلان')),
                ('audience', models.CharField(choices=[('all', 'الجميع'), ('graduates', 'الخريجون'), ('employers', 'جهات التوظيف'), ('staff', 'موظفو البوابة')], db_index=True, default='all', max_length=20, verbose_name='الفئة المستهدفة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='draft', max_length=20, verbose_name='حالة الإعلان')),
                ('target_filters', models.JSONField(blank=True, default=dict, verbose_name='معايير استهداف الإعلان')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الإعلان')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحملة')),
                ('target_filters', models.JSONField(blank=True, default=dict, verbose_name='معايير الاستهداف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدولة'), ('processing', 'قيد الإرسال'), ('completed', 'مكتملة'), ('cancelled', 'ملغية'), ('failed', 'فشلت')], db_index=True, default='draft', max_length=20, verbose_name='حالة الحملة')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الإرسال المجدول')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء الإرسال')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت اكتمال الإرسال')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='communications.messagetemplate', verbose_name='قالب الرسالة')),
            ],
            options={
                'verbose_name': 'حملة تواصل',
                'verbose_name_plural': 'حملات التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='نص الإشعار')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='رابط الإجراء')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='تمت القراءة')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('recipient_address', models.CharField(max_length=250, verbose_name='بريد أو رقم المستلم')),
                ('delivery_status', models.CharField(choices=[('pending', 'بانتظار الإرسال'), ('sent', 'مرسلة'), ('delivered', 'مستلمة'), ('opened', 'تم فتحها'), ('failed', 'فشل الإرسال'), ('unsubscribed', 'ألغى الاشتراك')], db_index=True, default='pending', max_length=20, verbose_name='حالة التسليم')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستلام')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت فتح الرسالة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('employer_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_messages', to='employers.employercontact', verbose_name='مسؤول جهة التوظيف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.communicationcampaign', verbose_name='الحملة')),
            ],
            options={
                'verbose_name': 'مستلم حملة',
                'verbose_name_plural': 'مستلمو الحملات',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'recipient_address'), name='unique_recipient_per_campaign')],
            },
        ),
    ]
