# Generated by Django 6.1 on 2026-08-20 07:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('name_ar', models.CharField(max_length=250, verbose_name='اسم الجهة بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=250, verbose_name='اسم الجهة بالإنجليزية')),
                ('sector_type', models.CharField(choices=[('government', 'حكومي'), ('private', 'خاص'), ('non_profit', 'غير ربحي'), ('international', 'دولي'), ('other', 'أخرى')], db_index=True, max_length=20, verbose_name='نوع القطاع')),
                ('industry', models.CharField(blank=True, max_length=150, verbose_name='مجال النشاط')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='رقم السجل أو التعريف')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('country', models.CharField(default='المملكة العربية السعودية', max_length=100, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('is_verified', models.BooleanField(default=False, verbose_name='جهة موثقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'جهة توظيف',
                'verbose_name_plural': 'جهات التوظيف',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='EmployerPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('partnership_type', models.CharField(choices=[('employment', 'توظيف'), ('training', 'تدريب'), ('surveys', 'استبانات وقياس'), ('general', 'تعاون عام')], max_length=20, verbose_name='نوع الشراكة')),
                ('status', models.CharField(choices=[('proposed', 'مقترحة'), ('active', 'نشطة'), ('expired', 'منتهية'), ('suspended', 'موقوفة')], db_index=True, default='proposed', max_length=20, verbose_name='حالة الشراكة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partnerships', to='employers.employer', verbose_name='جهة التوظيف')),
            ],
            options={
                'verbose_name': 'شراكة مع جهة توظيف',
                'verbose_name_plural': 'شراكات جهات التوظيف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='المسمى الوظيفي')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف صحيحًا، ويمكن أن يبدأ بعلامة +.', regex='^\\+?[0-9]{8,15}$')], verbose_name='رقم التواصل')),
                ('is_primary', models.BooleanField(default=False, verbose_name='جهة الاتصال الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='employers.employer', verbose_name='جهة التوظيف')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_contact', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'مسؤول جهة توظيف',
                'verbose_name_plural': 'مسؤولو جهات التوظيف',
                'ordering': ['employer', 'full_name'],
                'constraints': [models.UniqueConstraint(fields=('employer', 'email'), name='unique_contact_email_per_employer')],
            },
        ),
    ]
