# Generated by Django 6.1 on 2026-08-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('question', models.CharField(max_length=300, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('site_name', models.CharField(default='بوابة خدمات الخريجين', max_length=150, verbose_name='اسم البوابة')),
                ('university_name', models.CharField(max_length=200, verbose_name='اسم الجامعة')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد الدعم')),
                ('support_phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف الدعم')),
                ('privacy_policy_url', models.URLField(blank=True, verbose_name='رابط سياسة الخصوصية')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
            ],
            options={
                'verbose_name': 'إعداد البوابة',
                'verbose_name_plural': 'إعدادات البوابة',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط المختصر')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشورة')),
            ],
            options={
                'verbose_name': 'صفحة ثابتة',
                'verbose_name_plural': 'الصفحات الثابتة',
                'ordering': ['title'],
            },
        ),
    ]
