# Generated by Django 6.1 on 2026-08-20 07:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='رمز الكلية')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم الكلية بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='اسم الكلية بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='GraduationCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('academic_year', models.CharField(max_length=20, verbose_name='العام الأكاديمي')),
                ('semester', models.CharField(max_length=30, verbose_name='الفصل الدراسي')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التخرج')),
            ],
            options={
                'verbose_name': 'دفعة تخرج',
                'verbose_name_plural': 'دفعات التخرج',
                'ordering': ['-academic_year', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('code', models.CharField(max_length=30, verbose_name='رمز القسم')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم القسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='اسم القسم بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='academic_data.college', verbose_name='الكلية')),
            ],
            options={
                'verbose_name': 'قسم أكاديمي',
                'verbose_name_plural': 'الأقسام الأكاديمية',
                'ordering': ['college', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='رمز البرنامج')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم البرنامج بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='اسم البرنامج بالإنجليزية')),
                ('degree_level', models.CharField(choices=[('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('doctorate', 'دكتوراه')], max_length=20, verbose_name='الدرجة العلمية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_programs', to='academic_data.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'برنامج أكاديمي',
                'verbose_name_plural': 'البرامج الأكاديمية',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='GraduateAcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('student_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم الجامعي')),
                ('full_name_ar', models.CharField(max_length=250, verbose_name='الاسم بالعربية')),
                ('full_name_en', models.CharField(blank=True, max_length=250, verbose_name='الاسم بالإنجليزية')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='المعدل التراكمي')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التخرج')),
                ('source_system', models.CharField(blank=True, max_length=100, verbose_name='النظام المصدر')),
                ('source_last_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث من النظام المصدر')),
                ('is_verified', models.BooleanField(default=True, verbose_name='سجل موثق')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduate_records', to='academic_data.academicprogram', verbose_name='البرنامج الأكاديمي')),
            ],
            options={
                'verbose_name': 'سجل أكاديمي لخريج',
                'verbose_name_plural': 'السجلات الأكاديمية للخريجين',
                'ordering': ['-graduation_date', 'student_number'],
            },
        ),
    ]
