# Generated by Django 6.1 on 2026-08-20 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateacademicrecord',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_record', to=settings.AUTH_USER_MODEL, verbose_name='حساب الخريج'),
        ),
        migrations.AddConstraint(
            model_name='graduationcohort',
            constraint=models.UniqueConstraint(fields=('academic_year', 'semester'), name='unique_graduation_cohort'),
        ),
        migrations.AddField(
            model_name='graduateacademicrecord',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduate_records', to='academic_data.graduationcohort', verbose_name='دفعة التخرج'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('college', 'code'), name='unique_department_code_per_college'),
        ),
    ]
