# Generated by Django 6.1 on 2026-08-20 07:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('role', models.CharField(choices=[('graduate', 'خريج'), ('employer', 'ممثل جهة توظيف'), ('staff', 'موظف العمادة'), ('college_rep', 'ممثل كلية'), ('analyst', 'محلل بيانات'), ('system_admin', 'مدير النظام')], db_index=True, default='graduate', max_length=30, verbose_name='الدور')),
                ('university_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الرقم الجامعي أو الوظيفي')),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف صحيحًا، ويمكن أن يبدأ بعلامة +.', regex='^\\+?[0-9]{8,15}$')], verbose_name='رقم الجوال')),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'الإنجليزية')], default='ar', max_length=2, verbose_name='اللغة المفضلة')),
                ('email_verified', models.BooleanField(default=False, verbose_name='البريد موثق')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='يجب تغيير كلمة المرور')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['first_name', 'last_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('consent_type', models.CharField(choices=[('privacy', 'سياسة الخصوصية'), ('terms', 'شروط الاستخدام'), ('communications', 'استقبال الرسائل'), ('research', 'استخدام البيانات في الدراسات')], max_length=30, verbose_name='نوع الموافقة')),
                ('document_version', models.CharField(max_length=20, verbose_name='إصدار الوثيقة')),
                ('is_granted', models.BooleanField(default=True, verbose_name='تمت الموافقة')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الموافقة')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ سحب الموافقة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'موافقة مستخدم',
                'verbose_name_plural': 'موافقات المستخدمين',
                'constraints': [models.UniqueConstraint(fields=('user', 'consent_type', 'document_version'), name='unique_user_consent_version')],
            },
        ),
    ]
