# Generated by Django 6.1 on 2026-08-20 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('metric_code', models.CharField(db_index=True, max_length=100, verbose_name='رمز المؤشر')),
                ('metric_name', models.CharField(max_length=200, verbose_name='اسم المؤشر')),
                ('scope', models.CharField(default='university', max_length=100, verbose_name='نطاق المؤشر')),
                ('dimensions', models.JSONField(blank=True, default=dict, verbose_name='أبعاد المؤشر')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة المؤشر')),
                ('calculated_at', models.DateTimeField(verbose_name='وقت احتساب المؤشر')),
            ],
            options={
                'verbose_name': 'لقطة مؤشر',
                'verbose_name_plural': 'لقطات المؤشرات',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['metric_code', 'calculated_at'], name='metric_code_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('report_type', models.CharField(choices=[('graduate_profile', 'بيانات الخريجين'), ('employment', 'مؤشرات التوظيف'), ('employer_feedback', 'تقييم جهات التوظيف'), ('surveys', 'نتائج الاستبانات'), ('programs', 'البرامج التطويرية'), ('custom', 'تقرير مخصص')], db_index=True, max_length=30, verbose_name='نوع التقرير')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='مرشحات التقرير')),
                ('selected_columns', models.JSONField(blank=True, default=list, verbose_name='الأعمدة المختارة')),
                ('is_public_to_staff', models.BooleanField(default=False, verbose_name='متاح لموظفي البوابة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL, verbose_name='مشارك مع')),
            ],
            options={
                'verbose_name': 'تقرير محفوظ',
                'verbose_name_plural': 'التقارير المحفوظة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('export_format', models.CharField(choices=[('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=10, verbose_name='صيغة التصدير')),
                ('status', models.CharField(choices=[('pending', 'بانتظار المعالجة'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], db_index=True, default='pending', max_length=20, verbose_name='حالة التصدير')),
                ('file', models.FileField(blank=True, upload_to='report_exports/%Y/%m/', verbose_name='ملف التقرير')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء صلاحية الملف')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to=settings.AUTH_USER_MODEL, verbose_name='طلبه')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.savedreport', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'تصدير تقرير',
                'verbose_name_plural': 'عمليات تصدير التقارير',
                'ordering': ['-created_at'],
            },
        ),
    ]
