# Generated by Django 6.1 on 2026-08-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurtherStudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('institution_name', models.CharField(max_length=250, verbose_name='اسم المؤسسة التعليمية')),
                ('program_name', models.CharField(max_length=250, verbose_name='اسم البرنامج')),
                ('degree_level', models.CharField(max_length=100, verbose_name='الدرجة العلمية')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('expected_or_actual_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية المتوقع أو الفعلي')),
                ('status', models.CharField(choices=[('current', 'مستمر'), ('completed', 'مكتمل'), ('suspended', 'متوقف')], db_index=True, default='current', max_length=20, verbose_name='حالة الدراسة')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='further_studies', to='graduates.graduateprofile', verbose_name='الخريج')),
            ],
            options={
                'verbose_name': 'دراسة لاحقة',
                'verbose_name_plural': 'الدراسات اللاحقة',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GraduateCareerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('status', models.CharField(choices=[('employed', 'موظف'), ('self_employed', 'عمل حر أو صاحب عمل'), ('job_seeker', 'باحث عن عمل'), ('studying', 'يواصل الدراسة'), ('not_seeking', 'لا يبحث عن عمل'), ('unknown', 'غير محدد')], db_index=True, default='unknown', max_length=20, verbose_name='الحالة المهنية')),
                ('available_for_opportunities', models.BooleanField(default=False, verbose_name='متاح للفرص الوظيفية')),
                ('status_since', models.DateField(blank=True, null=True, verbose_name='الحالة منذ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('graduate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_status', to='graduates.graduateprofile', verbose_name='الخريج')),
            ],
            options={
                'verbose_name': 'حالة مهنية',
                'verbose_name_plural': 'الحالات المهنية',
            },
        ),
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('desired_job_titles', models.TextField(blank=True, verbose_name='المسميات الوظيفية المرغوبة')),
                ('preferred_cities', models.TextField(blank=True, verbose_name='المدن المفضلة')),
                ('preferred_sectors', models.TextField(blank=True, verbose_name='القطاعات المفضلة')),
                ('accepts_remote_work', models.BooleanField(default=True, verbose_name='يقبل العمل عن بعد')),
                ('accepts_relocation', models.BooleanField(default=False, verbose_name='يقبل الانتقال إلى مدينة أخرى')),
                ('expected_salary_range', models.CharField(blank=True, max_length=100, verbose_name='نطاق الراتب المتوقع')),
                ('graduate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preference', to='graduates.graduateprofile', verbose_name='الخريج')),
            ],
            options={
                'verbose_name': 'تفضيلات وظيفية',
                'verbose_name_plural': 'التفضيلات الوظيفية',
            },
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('employer_name', models.CharField(blank=True, max_length=250, verbose_name='اسم جهة العمل')),
                ('job_title', models.CharField(max_length=200, verbose_name='المسمى الوظيفي')),
                ('employment_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد'), ('internship', 'تدريب'), ('freelance', 'عمل حر'), ('business_owner', 'صاحب عمل')], max_length=20, verbose_name='نوع العمل')),
                ('country', models.CharField(default='المملكة العربية السعودية', max_length=100, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية العمل')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العمل')),
                ('is_current', models.BooleanField(db_index=True, default=True, verbose_name='عمل حالي')),
                ('is_primary', models.BooleanField(default=True, verbose_name='العمل الأساسي')),
                ('related_to_specialization', models.BooleanField(blank=True, null=True, verbose_name='مرتبط بالتخصص')),
                ('specialization_relevance_percentage', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='نسبة ارتباط العمل بالتخصص')),
                ('salary_range', models.CharField(blank=True, max_length=100, verbose_name='نطاق الراتب')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduate_employment_records', to='employers.employer', verbose_name='جهة التوظيف المسجلة')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='graduates.graduateprofile', verbose_name='الخريج')),
            ],
            options={
                'verbose_name': 'سجل وظيفي',
                'verbose_name_plural': 'السجلات الوظيفية',
                'ordering': ['-is_current', '-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True), ('is_primary', True)), fields=('graduate',), name='unique_primary_current_job')],
            },
        ),
    ]
