# Generated by Django 6.1 on 2026-08-20 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('access_type', models.CharField(choices=[('view_personal', 'عرض بيانات شخصية'), ('export', 'تصدير بيانات'), ('download', 'تنزيل مستند'), ('print', 'طباعة تقرير')], db_index=True, max_length=30, verbose_name='نوع الوصول')),
                ('resource_name', models.CharField(max_length=250, verbose_name='المورد')),
                ('purpose', models.CharField(blank=True, max_length=300, verbose_name='غرض الوصول')),
                ('records_count', models.PositiveIntegerField(default=0, verbose_name='عدد السجلات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل وصول للبيانات',
                'verbose_name_plural': 'سجلات الوصول للبيانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('view', 'عرض'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('export', 'تصدير'), ('send', 'إرسال'), ('approve', 'اعتماد'), ('reject', 'رفض')], db_index=True, max_length=20, verbose_name='العملية')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='معرف العنصر')),
                ('object_representation', models.CharField(blank=True, max_length=300, verbose_name='وصف العنصر')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='بيانات المتصفح')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='مسار الطلب')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='منفذ العملية')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع العنصر')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_target_idx'), models.Index(fields=['actor', 'created_at'], name='audit_actor_date_idx')],
            },
        ),
    ]
