# Generated by Django 6.1 on 2026-08-20 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('graduates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('question_type', models.CharField(choices=[('short_text', 'نص قصير'), ('long_text', 'نص طويل'), ('single_choice', 'اختيار واحد'), ('multiple_choice', 'اختيارات متعددة'), ('rating', 'مقياس تقييم'), ('number', 'رقم'), ('date', 'تاريخ'), ('boolean', 'نعم أو لا')], max_length=30, verbose_name='نوع السؤال')),
                ('is_required', models.BooleanField(default=False, verbose_name='السؤال إجباري')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('help_text', models.CharField(blank=True, max_length=300, verbose_name='نص مساعد')),
                ('validation_rules', models.JSONField(blank=True, default=dict, verbose_name='قواعد التحقق')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('label', models.CharField(max_length=250, verbose_name='نص الخيار')),
                ('value', models.CharField(max_length=100, verbose_name='قيمة الخيار')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'خيار سؤال',
                'verbose_name_plural': 'خيارات الأسئلة',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان الاستبانة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الاستبانة')),
                ('audience', models.CharField(choices=[('graduates', 'الخريجون'), ('employers', 'جهات التوظيف'), ('both', 'الخريجون وجهات التوظيف')], max_length=20, verbose_name='الفئة المستهدفة')),
                ('category', models.CharField(choices=[('graduate_outcomes', 'قياس مخرجات الخريجين'), ('employer_satisfaction', 'رضا أصحاب العمل'), ('program_evaluation', 'تقييم البرامج الأكاديمية'), ('training_needs', 'الاحتياجات التدريبية'), ('general', 'استبانة عامة')], db_index=True, default='general', max_length=30, verbose_name='تصنيف الاستبانة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشورة'), ('closed', 'مغلقة'), ('archived', 'مؤرشفة')], db_index=True, default='draft', max_length=20, verbose_name='حالة الاستبانة')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ فتح الاستبانة')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إغلاق الاستبانة')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='استبانة مجهولة الهوية')),
                ('allow_multiple_responses', models.BooleanField(default=False, verbose_name='السماح بأكثر من استجابة')),
                ('thank_you_message', models.TextField(blank=True, verbose_name='رسالة الشكر بعد الإرسال')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'استبانة',
                'verbose_name_plural': 'الاستبانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رمز الدعوة')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني للمستلم')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الإرسال'), ('sent', 'مرسلة'), ('opened', 'تم فتحها'), ('completed', 'مكتملة'), ('expired', 'منتهية')], db_index=True, default='pending', max_length=20, verbose_name='حالة الدعوة')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إرسال الدعوة')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ فتح الدعوة')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الدعوة')),
                ('employer_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_invitations', to='employers.employercontact', verbose_name='مسؤول جهة التوظيف')),
                ('graduate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_invitations', to='graduates.graduateprofile', verbose_name='الخريج')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='surveys.survey', verbose_name='الاستبانة')),
            ],
            options={
                'verbose_name': 'دعوة استبانة',
                'verbose_name_plural': 'دعوات الاستبانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('is_complete', models.BooleanField(db_index=True, default=False, verbose_name='الاستجابة مكتملة')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت بدء الاستجابة')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال الاستجابة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('employer_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='employers.employercontact', verbose_name='مسؤول جهة التوظيف')),
                ('graduate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='graduates.graduateprofile', verbose_name='الخريج')),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response', to='surveys.surveyinvitation', verbose_name='دعوة الاستبانة')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='الاستبانة')),
            ],
            options={
                'verbose_name': 'استجابة استبانة',
                'verbose_name_plural': 'استجابات الاستبانات',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('text_value', models.TextField(blank=True, verbose_name='الإجابة النصية')),
                ('number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الإجابة الرقمية')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='إجابة نعم أو لا')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='إجابة التاريخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.question', verbose_name='السؤال')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='selected_in_answers', to='surveys.questionoption', verbose_name='الخيارات المحددة')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse', verbose_name='استجابة الاستبانة')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
            },
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان القسم')),
                ('description', models.TextField(blank=True, verbose_name='وصف القسم')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.survey', verbose_name='الاستبانة')),
            ],
            options={
                'verbose_name': 'قسم استبانة',
                'verbose_name_plural': 'أقسام الاستبانة',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveysection', verbose_name='قسم الاستبانة'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='unique_option_value_per_question'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_answer_per_response_question'),
        ),
    ]
