# Generated by Django 6.1 on 2026-08-20 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_data', '0001_initial'),
        ('graduates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز البرنامج')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان البرنامج')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('program_type', models.CharField(choices=[('course', 'دورة'), ('workshop', 'ورشة عمل'), ('career_guidance', 'إرشاد مهني'), ('certification', 'شهادة مهنية'), ('mentoring', 'إرشاد وتوجيه'), ('event', 'فعالية')], max_length=30, verbose_name='نوع البرنامج')),
                ('delivery_mode', models.CharField(choices=[('in_person', 'حضوري'), ('online_live', 'عن بعد مباشر'), ('online_recorded', 'عن بعد مسجل'), ('hybrid', 'مدمج')], max_length=30, verbose_name='طريقة التقديم')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('open', 'التسجيل متاح'), ('closed', 'التسجيل مغلق'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='السعة')),
                ('registration_starts_at', models.DateTimeField(blank=True, null=True, verbose_name='بداية التسجيل')),
                ('registration_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية التسجيل')),
                ('starts_at', models.DateTimeField(verbose_name='بداية البرنامج')),
                ('ends_at', models.DateTimeField(verbose_name='نهاية البرنامج')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='الموقع')),
                ('meeting_url', models.URLField(blank=True, verbose_name='رابط الحضور')),
                ('eligibility_rules', models.JSONField(blank=True, default=dict, verbose_name='شروط الأهلية')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_development_programs', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('target_academic_programs', models.ManyToManyField(blank=True, related_name='development_programs', to='academic_data.academicprogram', verbose_name='البرامج الأكاديمية المستهدفة')),
            ],
            options={
                'verbose_name': 'برنامج تطويري',
                'verbose_name_plural': 'البرامج التطويرية',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('confirmed', 'مؤكد'), ('waitlisted', 'قائمة انتظار'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], db_index=True, default='pending', max_length=20, verbose_name='حالة التسجيل')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_registrations', to='graduates.graduateprofile', verbose_name='الخريج')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='programs.developmentprogram', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'تسجيل في برنامج',
                'verbose_name_plural': 'التسجيلات في البرامج',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رمز التحقق')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('certificate_file', models.FileField(blank=True, upload_to='program_certificates/%Y/%m/', verbose_name='ملف الشهادة')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='programs.programregistration', verbose_name='التسجيل')),
            ],
            options={
                'verbose_name': 'شهادة برنامج',
                'verbose_name_plural': 'شهادات البرامج',
            },
        ),
        migrations.CreateModel(
            name='ProgramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان الجلسة')),
                ('trainer_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المدرب')),
                ('starts_at', models.DateTimeField(verbose_name='بداية الجلسة')),
                ('ends_at', models.DateTimeField(verbose_name='نهاية الجلسة')),
                ('location_or_url', models.CharField(blank=True, max_length=500, verbose_name='الموقع أو الرابط')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='programs.developmentprogram', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'جلسة برنامج',
                'verbose_name_plural': 'جلسات البرامج',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('attended', models.BooleanField(default=False, verbose_name='حضر')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الحضور')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='programs.programregistration', verbose_name='التسجيل')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='programs.programsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'حضور جلسة',
                'verbose_name_plural': 'سجلات الحضور',
            },
        ),
        migrations.AddConstraint(
            model_name='programregistration',
            constraint=models.UniqueConstraint(fields=('program', 'graduate'), name='unique_program_registration_per_graduate'),
        ),
        migrations.AddConstraint(
            model_name='sessionattendance',
            constraint=models.UniqueConstraint(fields=('registration', 'session'), name='unique_attendance_per_session'),
        ),
    ]
