# Generated by Django 6.1 on 2026-08-20 07:45

import django.core.validators
import django.db.models.deletion
import graduates.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('name_ar', models.CharField(max_length=150, unique=True, verbose_name='اسم المهارة بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='اسم المهارة بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'مهارة',
                'verbose_name_plural': 'المهارات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='GraduateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى'), ('not_specified', 'غير محدد')], default='not_specified', max_length=20, verbose_name='الجنس')),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الشخصي')),
                ('primary_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف صحيحًا، ويمكن أن يبدأ بعلامة +.', regex='^\\+?[0-9]{8,15}$')], verbose_name='رقم الجوال')),
                ('alternative_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف صحيحًا، ويمكن أن يبدأ بعلامة +.', regex='^\\+?[0-9]{8,15}$')], verbose_name='رقم جوال بديل')),
                ('country', models.CharField(default='المملكة العربية السعودية', max_length=100, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='حساب LinkedIn')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='الموقع أو معرض الأعمال')),
                ('profile_status', models.CharField(choices=[('incomplete', 'غير مكتمل'), ('complete', 'مكتمل'), ('needs_review', 'يحتاج مراجعة')], db_index=True, default='incomplete', max_length=20, verbose_name='حالة الملف')),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='نسبة اكتمال الملف')),
                ('allow_email_contact', models.BooleanField(default=True, verbose_name='السماح بالتواصل عبر البريد')),
                ('allow_sms_contact', models.BooleanField(default=False, verbose_name='السماح بالتواصل عبر الرسائل')),
                ('last_profile_review_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مراجعة للملف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف خريج',
                'verbose_name_plural': 'ملفات الخريجين',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='GraduateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('document_type', models.CharField(choices=[('cv', 'السيرة الذاتية'), ('certificate', 'شهادة'), ('portfolio', 'معرض أعمال'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الملف')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الملف')),
                ('file', models.FileField(upload_to=graduates.models.graduate_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='الملف')),
                ('is_visible_to_employers', models.BooleanField(default=False, verbose_name='ظاهر لجهات التوظيف')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='graduates.graduateprofile', verbose_name='الخريج')),
            ],
            options={
                'verbose_name': 'مستند خريج',
                'verbose_name_plural': 'مستندات الخريجين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraduateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('proficiency_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('expert', 'خبير')], max_length=20, verbose_name='مستوى الإتقان')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='graduates.graduateprofile', verbose_name='الخريج')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduates', to='graduates.skill', verbose_name='المهارة')),
            ],
            options={
                'verbose_name': 'مهارة خريج',
                'verbose_name_plural': 'مهارات الخريجين',
                'constraints': [models.UniqueConstraint(fields=('graduate', 'skill'), name='unique_skill_per_graduate')],
            },
        ),
    ]
